# Generated by Django 5.2.1 on 2025-06-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('year_of_exp', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('specialization', models.CharField(max_length=255)),
                ('total_cases', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lawfirm_images/')),
            ],
        ),
    ]
