# Generated by Django 5.2.1 on 2025-06-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=100)),
                ('case_description', models.TextField()),
                ('case_image', models.ImageField(blank=True, null=True, upload_to='caseimage/')),
            ],
        ),
    ]
